### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by toomanycats** [CBICA/MASS#2]
Cloned master and trying to build. 

    $ cmake -D CMAKE_INSTALL_PREFIX=$PWD -D SCHEDULER:STRING=SGE ../src
    CMake Error at CMakeLists.txt:100 (install):
     install FILES given no DESTINATION!

I think this is related to the warning that the cmake version is not being set and the `project` command is not being used.
I see both of those commands in the top level `CMakeLists.txt` file. For some reason it is not parsed.

cmake version 3.16.3

**Comment by toomanycats** [comment]
I think the solution, is to think of the `src/CMakeLists.txt` as the entry point. 
Place the `project()` call and set the CMAKE version in that, and include the root CMakeLists.txt.

I'll submit a PR when I get a chance to test. Otherwise, I cannot see how CMAKE knows what the root of the project is.

**Comment by toomanycats** [comment]
My fix on CMakeLists.txt seems to work as I don't get the original error. However now I get a seg fault during the build.

**Comment by gurayerus** [comment]
Hi, it may take some time to replicate this issue and debug it, as our the developer of the package is not available now. We have an alternative deep learning based brain mask extraction package. Would you consider using it in the meantime? Or, do you specifically need to run MASS? If the first option works, please check 
 https://github.com/CBICA/DeepMRSeg
This package is a generic segmentation tool and it has trained models for brain mask (actually ICV mask) segmentation.

**Comment by toomanycats** [comment]
Thanks @gurayerus I actually solved it. Partly my fault for being new to CMAKE and partly an old `INSTALL.txt` file.
MASS builds with a small modification to the command:

    mkdir build && cd build
    cmake -D CMAKE_INSTALL_PREFIX:STRING=/Full/path/to/install/mass/    \
    	   -D SCHEDULER:STRING=??? .. 

I was very confused how the build would pick up the top level `CMakeLists.txt` and finally realized that you just point to it :|
Thanks for you response.
